### ISSUE TITLE
Missing releases :D

### ISSUE THREAD

**Issue by MasterPIC** [je-lamiaud/phd2#5]
Hi Jean-Etienne Lamiaud,

I'd like to switch to your fork because of simultaneous guiding (I asked for this feature but frankly I got a not really nice feedback) and guiding exposure sync issues with QHY cameras.

Could you upload a release ready to use?

Sorry for opening an issue just to ask for a release. 

Clear Skies!
Armando Beneduce

**Comment by je-lamiaud** [comment]
Sorry, I've missed your post.

Unfortunately, I'm able to build an executable for running on my own computer, but when I look at its dependencies, there are libraries in uncommon places which precludes running on anyone else's machine.

Which Operating System are you using ? I may be able to try to get rid of these peculiar library paths on macOS and Linux, but do not have any Windows setup to even compile. In the latter case, we would need assistance from some other GitHub developper.

**Comment by je-lamiaud** [comment]
Which guiding mount are you using ?
Currently, the simultaneous guiding is supported only on the INDI mount (and my homemade EQTrack, which is obviously not relevant here 🙂). But it is quite easy to add the capability to another mount.
If you are using the ST4 guiding port of the QHY camera, I can have a look at it, owning myself a QHY5 III 178.

Clear skies to you too.
Jean-Etienne

**Comment by MasterPIC** [comment]
According to documentation, PulseGuide method returns immediately if the hardware is capable of back-to-back moves e.g. dual-axis moves. For hardware not having dual-axis capability, the method returns only after the move has completed.
So I think ASCOM doesn't exclude simultaneous guiding.
I'm currently guiding by ASCOM by a QHY5L-II. I can also guide by ST-4. AFAIK QHY5L-II offers simultaneous guiding by ST-4.

**Comment by je-lamiaud** [comment]
Hello. I've tested the ST4 interface of my QHY5 III 178.
I see the ST4 RA and Dec signals being activated one after another, never simultaneously. A look at the debug traces confirms that the QHYCCD API call is indeed blocking until the end of each move.
That is probably "hardware not having dual-axis capability". Too bad 🙁
I had a look at the ASCOM code in PHD2, it is quite easy to migrate to dual-axis guiding. I'll let you know when it is available. But, the ASCOM scope is Windows only, and I do not have any Windows setup. In order to test this change, either you will build PHD2 yourself from this fork, or we need to find someone who can help.

By the way
> frankly I got a not really nice feedback

I know what you're talking about, you're not alone 😉

**Comment by MasterPIC** [comment]
I already tried to build from your fork but unsuccessfully (probably a wrong VS version).
Anyway I can try again to build your source code...

Thanks again

**Comment by je-lamiaud** [comment]
Well. When you don't even have a setup to compile the source, things are not that easy. It is actually some kind of blindfolded coding....
I was hoping to get my hand on a Windows PC during a one week holiday on the first week of July, but came up empty handed.
I recently succeeded in using a PC, with limited rights, anyway enough to get the "scope_ascom.cpp" file compiled without errors; but not to build the complete application (lots of missing DLLs).

You can find this ASCOM driver with tentative dual axis capability In the "ascom-dual-axis" branch.
This is as far as I could get. I hope you will be able to build the PHD2 application from this, and test it. If you succeed (and maybe after some further corrections 🙂), I will merge this in the "garage" branch.

**Comment by MasterPIC** [comment]
Hi,

I was able to build your source code. I just added a pair of comments (linux related code) and, as I had compiling issues previously, I changed a file as I noticed a commit to fix build issues on Windows not included by you.

I made a test by camera and mount simulators.
The screenshot that follows seems to confirm simultaneous guiding works as expected: as soon as I set simulltaneous guiding I had both pulse guiding commands initiated and then completed...

![image](https://github.com/user-attachments/assets/392cc508-8778-40ae-ae29-5a8f0f411d2d)

I'll provide further details after appropriate tests.
In the meantime thank you so much!

CS
Armando

**Comment by MasterPIC** [comment]
I made another test still by simulators but connected to my mount controller.

![TestBySHC](https://github.com/user-attachments/assets/b2303e98-ed0e-4451-bfed-4264064bdba5)

You can see simultaneous guiding reported by the hand controller display.
Cheating with calibration values (to force higher/lower pulse duration on Dec) I found the RA arrows indicator ending before/after DEC ones as expected.

What is missing is a real test under the sky. I'll let you know.

Thanks
Armando

**Comment by je-lamiaud** [comment]
Great !

Sure the mount behavior is key. I recently purchased an iOptron HEM15, which "accepts" the simultaneous guide commands, but actually cancels the first pulse when the second command is received. I did this check without PHD2, by sending HTTP commands to my Indigo server, and checking the star movement on the guide camera.

But, in your case, if the hand controller (which is the key part of the mount) responds correctly that's a great stride.

BTW, I had taken note of the new commits in the original PHD2, but was waiting to stabilize the ASCOM topic before merging; because one of these commits disrupts the files location, and promises headaches when merging 😅

**Comment by je-lamiaud** [comment]
I have merged with the original PHD2 (and actually it went like a breeze). The Windows build fix was part of the merge.
If you have some additional changes, you can make a Pull Request, which I can incorporate into this repository.

I have created a release (https://github.com/je-lamiaud/phd2/releases/tag/v2.6.13dev5-fork), which currently only contains the macOS application. Do you think you can provide the Windows one ?

**Comment by MasterPIC** [comment]
I built your updated code from garage branch and tested it under the sky. 
I think it works flawlessly. 
Anyway I wasn't able to build the installer. I'll let you know...

**Comment by MasterPIC** [comment]
I can upload a zip containing the folder: it should work as portable.

**Comment by je-lamiaud** [comment]
Great !
I love portable apps 🙂 That's the only thing I can "install" on the Windows PC I have access to. Installers are the privilege of administrators, which I'm not.

I've invited you to the collaborators of this fork. When this is complete, you should be able to upload a zip archive directly in the release.

**Comment by je-lamiaud** [comment]
I have run the portable app on a Windows PC.
It does work. I even could use the integrated webcam.
This topic can now be closed.
